
version: '3'
services:

  api-gateway:
     image: 01tanmay/fse-a2m:api-gateway
     restart: on-failure
     #network_mode: host
     container_name: api-gateway
     #depends_on: 
     # - mongo
     ports:
      - 8080:8080
      
  user-auth:
    image: 01tanmay/fse-a2m:user-auth
    restart: on-failure
    #network_mode: host
    container_name: user-auth
    #depends_on: 
    #  - mysql
    ports:
      - 8081:8081
    #build:
    #    context:"./"
    #    dockerfile:"Dockerfile"
    #envronment:
    #    SPRING_DATASOURCE_URL:

  stock-price:
     image: 01tanmay/fse-a2m:stock-price
     restart: on-failure
     #network_mode: host
     container_name: stock-price
     #depends_on: 
     # - mongo
     ports:
      - 8082:8082
      
  company-details:
     image: 01tanmay/fse-a2m:company-details
     restart: on-failure
     #network_mode: host
     container_name: company-details
     #depends_on: 
     # - mongo
     ports:
      - 8083:8083
  
  eureka-server:
     image: 01tanmay/fse-a2m:eureka-server
     restart: on-failure
     #network_mode: host
     container_name: eureka-server
     #depends_on: 
     #- mongo
     ports:
      - 8761:8761
  
  #stockmarket-ui:
     #image: 01tanmay/fse-a2m:stockmarket-ui
     #restart: on-failure
     #network_mode: host
     #container_name: stockmarket-ui
     #depends_on: 
     # - mongo
     #ports:
      #- 4200:4200
      
  #mysql:
    #image: mysql:latest
    #ports:
     # - 3306:3306
    #network_mode: host
    #environment: 
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_HOST: localhost
      #MYSQL_DATABASE: ftb15
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
      #MYSQL_URL: jdbc:mysql://localhost:3306/ftb15

  mongo:
    image: mongo:latest
    restart: always
    ports: 
     - 27017:27017
    container_name: mongo
    #network_mode: host
      
