package com.stockmarket.companydetails.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
//import org.springframework.data.annotation.Id;
//import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.NotBlank;

@NoArgsConstructor
@AllArgsConstructor
@Data
@DynamoDBTable(tableName = "company")
//@Document(collection = "company")
public class Company {

    //@Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @NotBlank
    private String companyId;

    @DynamoDBAttribute
    @NotBlank(message = "Name is mandatory")
    private String name;

    @DynamoDBAttribute
    @NotBlank
    private String companyCode;

    @DynamoDBAttribute
    @NotBlank
    private String ceo;

    @DynamoDBAttribute
    @NotBlank
    private double turnover;

    @DynamoDBAttribute
    @NotBlank
    private String website;

    @DynamoDBAttribute
    @NotBlank(message = "Enter traded Exchange")
    private String stockExchange;

}
